from __future__ import annotations

from pathlib import Path

from reqahe.infra.io import ensure_dir, write_json, write_text
from reqahe.runtime.dataset import resolve_dataset_path
from reqahe.runtime.reqelicit_session import source_reqelicitgym_available
from reqahe.utils.paths import resolve_project_path, to_posix_relpath


def inspect_sources(
    project_root: str | Path,
    reqelicitgym_root: str | Path,
    dataset_file: str | None = None,
    dataset_number: int | str | None = None,
) -> Path:
    """Inspect in-repo ReqElicitGym sources and write relative-path notes."""
    project = Path(project_root).resolve()
    reqelicit = resolve_project_path(reqelicitgym_root, project)
    notes = ensure_dir(project / "notes")
    available, import_error = source_reqelicitgym_available(reqelicit)
    dataset_path = resolve_dataset_path(reqelicit, dataset_file=dataset_file, dataset_number=dataset_number)

    paths = {
        "reqelicit_dataset": dataset_path,
        "reqelicit_env": reqelicit / "env" / "reqelicit_gym.py",
        "reqelicit_prompts": reqelicit / "env" / "prompts.py",
    }
    configured_roots = {
        "project_root": ".",
        "reqelicitgym_root": to_posix_relpath(reqelicit, project),
    }
    display_paths = {key: to_posix_relpath(path, project) for key, path in paths.items()}

    lines = [
        "# Source Inspection",
        "",
        "This file is generated by `python -m reqahe.cli inspect`.",
        "",
        "## ReqElicitGym",
        "",
        f"- Root: `<REQELICITGYM_ROOT>` (config: `{configured_roots['reqelicitgym_root']}`)",
        f"- Dataset: `{display_paths['reqelicit_dataset']}` exists={paths['reqelicit_dataset'].exists()}",
        f"- Environment: `{display_paths['reqelicit_env']}` exists={paths['reqelicit_env'].exists()}",
        f"- Oracle/Judge prompts: `{display_paths['reqelicit_prompts']}` exists={paths['reqelicit_prompts'].exists()}",
        f"- Import available: {available}",
        f"- Import error: {import_error or '(none)'}",
        "",
        "## Metric Mapping",
        "",
        "- ReqAHE rollout uses ReqElicitGym `evaluate_action` (judge -> user) for all scoring.",
        "- IRE follows ReqElicitGym `elicitation_ratio`; TKQR follows `_calculate_tkqr` (log2 turn discount).",
        "- `probe_effectiveness` reports probe/clarify action effectiveness from judge relevance labels.",
        "",
        "## Result Notes",
        "",
        "- `internal evolution result` uses ReqAHE-generated train/val/test splits or configured task selections.",
        "- `final evaluation result` evaluates a frozen selected harness through the same ReqElicitGym interface.",
    ]
    out = notes / "source_inspection.md"
    write_text(out, "\n".join(lines) + "\n")
    write_json(
        notes / "source_inspection.json",
        {
            "configured_roots": configured_roots,
            **display_paths,
            "reqelicitgym_import_available": available,
            "import_error": import_error or "",
        },
    )
    return out
