from __future__ import annotations

from pathlib import Path

from reqahe.envs.dataset import resolve_dataset_path
from reqahe.envs.reqelicit import source_reqelicitgym_available
from reqahe.utils.io import ensure_dir, write_json, write_text


def inspect_sources(
    project_root: str | Path,
    typoagent_root: str | Path,
    reqelicitgym_root: str | Path,
    ahe_root: str | Path,
    dataset_file: str | None = None,
    dataset_number: int | str | None = None,
) -> Path:
    project = Path(project_root)
    notes = ensure_dir(project / "notes")
    available, import_error = source_reqelicitgym_available(reqelicitgym_root)
    dataset_path = resolve_dataset_path(reqelicitgym_root, dataset_file=dataset_file, dataset_number=dataset_number)
    paths = {
        "ahe_evolve": Path(ahe_root) / "evolve.py",
        "ahe_config": Path(ahe_root) / "configs" / "base.yaml",
        "typoagent_interviewer": Path(typoagent_root) / "TypoAgent" / "retriever" / "interviewer.py",
        "typoagent_builder": Path(typoagent_root) / "run_typobuilder.py",
        "typoagent_run_missing": Path(typoagent_root) / "run_typoagent.py",
        "reqelicit_dataset": dataset_path,
        "reqelicit_env": Path(reqelicitgym_root) / "env" / "reqelicit_gym.py",
        "reqelicit_prompts": Path(reqelicitgym_root) / "env" / "prompts.py",
    }
    lines = [
        "# Source Inspection",
        "",
        "This file is generated by `python -m reqahe.cli inspect`.",
        "",
        "## AHE",
        "",
        f"- Root: `{ahe_root}`",
        f"- Outer loop candidate: `{paths['ahe_evolve']}` exists={paths['ahe_evolve'].exists()}",
        "- The RE-AHE implementation reuses the phase structure conceptually, not Harbor/E2B/pass@1.",
        "- Harness evolution is mapped to prompt/tool/middleware/skills/memory workspace edits plus `change_manifest.json`.",
        "",
        "## TypoAgent / OntoAgent",
        "",
        f"- Root: `{typoagent_root}`",
        f"- `TypoAgentInterviewer`: `{paths['typoagent_interviewer']}` exists={paths['typoagent_interviewer'].exists()}",
        f"- Ontology builder: `{paths['typoagent_builder']}` exists={paths['typoagent_builder'].exists()}",
        f"- README-referenced `run_typoagent.py`: `{paths['typoagent_run_missing']}` exists={paths['typoagent_run_missing'].exists()}",
        "- `local_ontoagent` will be non-blocking: cache/build/import failures produce `local_ontoagent_unavailable_reason`.",
        "",
        "## ReqElicitGym",
        "",
        f"- Root: `{reqelicitgym_root}`",
        f"- Dataset: `{paths['reqelicit_dataset']}` exists={paths['reqelicit_dataset'].exists()}",
        f"- Environment: `{paths['reqelicit_env']}` exists={paths['reqelicit_env'].exists()}",
        f"- Oracle/Judge prompts: `{paths['reqelicit_prompts']}` exists={paths['reqelicit_prompts'].exists()}",
        f"- Import available: {available}",
        f"- Import error: {import_error or '(none)'}",
        "",
        "## Metric Mapping",
        "",
        "- ReqElicitGym exposes `elicitation_ratio` semantics for IRE and `_calculate_tkqr` semantics for TKQR.",
        "- A standalone ESR implementation was not identified during initial inspection. ReqAHE reports `approx_ESR` unless a source ESR implementation is later discovered.",
        "- `approx_ESR` is based on turn-level evaluator action labels and hit results; it is not treated as the paper ESR.",
        "",
        "## Fairness Notes",
        "",
        "- `internal_holdout_result` uses ReqAHE-generated train/val/test splits.",
        "- `paper_style_result` evaluates a frozen best harness on the full configured ReqElicitGym scenario dataset.",
        "- If evolution used any scenario from the configured evaluation dataset, paper-style results are marked `not strictly paper-fair`.",
    ]
    out = notes / "source_inspection.md"
    write_text(out, "\n".join(lines) + "\n")
    write_json(notes / "source_inspection.json", {k: str(v) for k, v in paths.items()} | {"reqelicitgym_import_available": available, "import_error": import_error})
    return out
